[project]
name = "human-posture-estimation"
version = "0.1.0"
description = "Industrial Human Posture AI Inspector"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python-headless>=4.8.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "fastapi>=0.100.0",
    "python-multipart>=0.0.9",
    "uvicorn>=0.22.0",
    "joblib>=1.3.0",
    "pillow>=10.0.0"
]

[tool.vercel]
entrypoint = "main:app"
